### ISSUE TITLE
[crash] java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper

### ISSUE THREAD

**Issue by sbrl** [Treer/amidstest#23]
Hello,

I've just started the latest release of amidstest today, and found that I'm getting a crash. I'm including the transcript at the bottom of this issue. Additional system information:

 - OS: Ubuntu 18.04
 - `uname -a`: `Linux Riikaan 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
 - Desktop: Unity 7.5.0
 - CPU: `Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz` (64 bits)
 - Java version: `openjdk 10.0.2 2018-07-17`

....more details available upon request - I just can't think of anything else useful to include :P

## Transcript

```
[info] Amidstest v1.2-beta
[info] Current system time: 2018-08-28 16:13:25.33
[info] System.getProperty("os.name") == 'Linux'
[info] System.getProperty("os.version") == '4.15.0-33-generic'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '10.0.2'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[crash] Amidst has encounted an uncaught exception on the thread Thread[main,5,main]
[crash] java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.desktop/java.awt.Toolkit.newAWTError(Toolkit.java:472)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:488)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1608)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:532)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:613)
	at java.desktop/java.awt.Toolkit.getEventQueue(Toolkit.java:1494)
	at java.desktop/java.awt.EventQueue.invokeLater(EventQueue.java:1312)
	at java.desktop/javax.swing.SwingUtilities.invokeLater(SwingUtilities.java:1421)
	at amidst.Amidst.startApplication(Amidst.java:162)
	at amidst.Amidst.run(Amidst.java:82)
	at amidst.Amidst.parseCommandLineArgumentsAndRun(Amidst.java:50)
	at amidst.Amidst.main(Amidst.java:30)
Caused by: java.lang.ClassNotFoundException: org.GNOME.Accessibility.AtkWrapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:485)
	... 18 more
```

**Comment by Treer** [comment]
[It sounds like you have a headless JDK installed](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=798794#10)

Stack exchange suggests either [uninstalling OpenJDK 8 headless and installing OpenJDK 8](https://askubuntu.com/questions/695560/assistive-technology-not-found-awterror), or [disabling assistive technologies](https://askubuntu.com/a/723503).
The bottom comment in the stack exchange thread indicates you can disable assistive technologues by appending `-Djavax.accessibility.assistive_technologies=" "` to your command.

Let me know if this solves the problem, and I'll add "Assistive Technology not found" to the wiki.

**Comment by sbrl** [comment]
Ah, thanks @Treer! I'm not much of a Java person :P

I had to edit `/etc/java-11-openjdk/accessibility.properties` as well as `/etc/java-8-openjdk/accessibility.properties` - and then it worked :smiley_cat:
