### ISSUE TITLE
Biome profile list is unpopulated

### ISSUE THREAD

**Issue by tacotexmex** [Treer/amidstest#6]
![upqsntp-1](https://user-images.githubusercontent.com/25328789/39248179-abed41f2-489b-11e8-9f01-98fe2b6ffab6.png)

On my system, the biome profile list is unpopulated. Clicking _Edit biome profiles_ opens up the `biome` folder that is generated **in the same directory** as the jar file. That folder seems to hold all the right files:
```
30-biomes.mt
Ethereal.mt
MineClone 2.mt
Minetest default.mt
V6 biomes.mt
VoxelGarden.mt
VoxelGardon.mt
```

Another indication that the application doesn't recognize the folder is that the title bar says the following `(recognised: UNKNOWN)`:

<img width="661" alt="skarmavbild 2018-04-25 kl 15 24 14" src="https://user-images.githubusercontent.com/25328789/39248635-ec31705c-489c-11e8-8d3b-11f2fc1d9532.png">

macOS 10.12.6, Java 10.0.1, amidst (beta, beta 2, beta 3)

**Comment by Treer** [comment]
Thanks, I'll look into it, I think macOS is probably a relevant clue here as it's the OS I can't test on, and it has its own appropriate path for application data - which Amidstest is clearly not using.

**Comment by tacotexmex** [comment]
Is it that the app data folder should reside in `~/Library/Application Support/`? If so I can test moving the folder there.

**Comment by Treer** [comment]
Yeah, it's [trying to put it into ~/Library/Application Support/amidstest/](https://github.com/Treer/amidstest/blob/master/src/main/java/amidst/settings/biomeprofile/BiomeProfileDirectory.java#L61)


it'd be useful to see if moving the biome folder there fixes the problem, but I suspect that chunk of code may have bigger issues than OSX. It might not be fully working under the other OSes either, so I might be able to fix it just with scrutiny rather than needing a mac, however if I need a mac I might be able to get one running in a VM.

(clicked wrong button, didn't mean to close issue)

**Comment by tacotexmex** [comment]
Oh, `~/Library/Application/` doesn't and shouldn't exist on macOS. I suspect that in order for the program to not cut the path off at the space you need to use either `~/Library/Application\ Support/amidstest/` or `"~/Library/Application Support/amidstest/"`.

I tried putting `biome` in both `~/Library/Application/amidstest/` and in `~/Library/Application Support/amidstest/` to no avail, and it still creates a new `biome` besides the jar file.

Yes, VirtualBox should be able to virtualize macOS.

**Comment by Treer** [comment]
While you're experimenting with it, are there any errors in the log when you run it? 

Click on Help->Display Log messages

**Comment by tacotexmex** [comment]
Yes, here's my log when having a `~/Library/Application Support/amidstest/biomes/` present. It successfully downloads and stores the list but then it cannot find it for loading.

```
[info] Amidstest v1.0-beta3
[info] Current system time: 2018-04-26 10:32:50.73
[info] System.getProperty("os.name") == 'Mac OS X'
[info] System.getProperty("os.version") == '10.12.6'
[info] System.getProperty("os.arch") == 'x86_64'
[info] System.getProperty("java.version") == '9.0.4'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Enabling OpenGL.
[info] Biome profile activated: default
[info] Minetest directory not found, using default mapgen v7 profile
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[info] Found biome profile directory.
[info] Saved default biome profile "Minetest default"
[info] Saved default biome profile "V6 biomes"
[info] Saved default biome profile "30-biomes"
[info] Saved default biome profile "Ethereal"
[info] Saved default biome profile "VoxelGarden"
[info] Saved default biome profile "MineClone 2"
[info] Biome profile activated: Minetest default
[info] Checking for additional biome profiles.
[info] Found biome profile directory.
[info] Found default biome profile "Minetest default"
[info] Found default biome profile "V6 biomes"
[info] Found default biome profile "30-biomes"
[info] Found default biome profile "Ethereal"
[info] Found default biome profile "VoxelGarden"
[info] Found default biome profile "MineClone 2"
[warning] Unable to load file: biome/30-biomes.mt
[warning] amidst.parsing.FormatException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 118 path $.biomeList[0].00
	at amidst.parsing.json.JsonReader.readReader(JsonReader.java:48)
	at amidst.parsing.json.JsonReader.readLocation(JsonReader.java:25)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.createFromFile(BiomeProfileDirectory.java:223)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.visitProfiles(BiomeProfileDirectory.java:170)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.visitProfiles(BiomeProfileDirectory.java:162)
	at amidst.gui.main.menu.BiomeProfileMenuFactory.initParentMenu(BiomeProfileMenuFactory.java:169)
	at amidst.gui.main.menu.BiomeProfileMenuFactory.<init>(BiomeProfileMenuFactory.java:161)
	at amidst.gui.main.menu.AmidstMenuBuilder.create_Settings_BiomeProfile(AmidstMenuBuilder.java:161)
	at amidst.gui.main.menu.AmidstMenuBuilder.create_Settings(AmidstMenuBuilder.java:129)
	at amidst.gui.main.menu.AmidstMenuBuilder.createMenuBar(AmidstMenuBuilder.java:54)
	at amidst.gui.main.menu.AmidstMenuBuilder.<init>(AmidstMenuBuilder.java:36)
	at amidst.gui.main.PerMainWindowInjector.<init>(PerMainWindowInjector.java:114)
	at amidst.PerApplicationInjector.createMainWindow(PerApplicationInjector.java:122)
	at amidst.Application.displayMainWindow(Application.java:73)
	at amidst.Application.run(Application.java:55)
	at amidst.Amidst.doStartApplication(Amidst.java:171)
	at amidst.Amidst.lambda$startApplication$0(Amidst.java:162)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 118 path $.biomeList[0].00
	at com.google.gson.Gson.fromJson(Gson.java:876)
	at com.google.gson.Gson.fromJson(Gson.java:799)
	at amidst.parsing.json.JsonReader.readReader(JsonReader.java:41)
	... 30 more
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 118 path $.biomeList[0].00
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1574)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:534)
	at com.google.gson.stream.JsonReader.skipValue(JsonReader.java:1237)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
	at com.google.gson.Gson.fromJson(Gson.java:861)
	... 32 more

[warning] Unable to load file: biome/Ethereal.mt
[warning] amidst.parsing.FormatException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 114 path $.biomeList[0].00
	at amidst.parsing.json.JsonReader.readReader(JsonReader.java:48)
	at amidst.parsing.json.JsonReader.readLocation(JsonReader.java:25)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.createFromFile(BiomeProfileDirectory.java:223)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.visitProfiles(BiomeProfileDirectory.java:170)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.visitProfiles(BiomeProfileDirectory.java:162)
	at amidst.gui.main.menu.BiomeProfileMenuFactory.initParentMenu(BiomeProfileMenuFactory.java:169)
	at amidst.gui.main.menu.BiomeProfileMenuFactory.<init>(BiomeProfileMenuFactory.java:161)
	at amidst.gui.main.menu.AmidstMenuBuilder.create_Settings_BiomeProfile(AmidstMenuBuilder.java:161)
	at amidst.gui.main.menu.AmidstMenuBuilder.create_Settings(AmidstMenuBuilder.java:129)
	at amidst.gui.main.menu.AmidstMenuBuilder.createMenuBar(AmidstMenuBuilder.java:54)
	at amidst.gui.main.menu.AmidstMenuBuilder.<init>(AmidstMenuBuilder.java:36)
	at amidst.gui.main.PerMainWindowInjector.<init>(PerMainWindowInjector.java:114)
	at amidst.PerApplicationInjector.createMainWindow(PerApplicationInjector.java:122)
	at amidst.Application.displayMainWindow(Application.java:73)
	at amidst.Application.run(Application.java:55)
	at amidst.Amidst.doStartApplication(Amidst.java:171)
	at amidst.Amidst.lambda$startApplication$0(Amidst.java:162)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 114 path $.biomeList[0].00
	at com.google.gson.Gson.fromJson(Gson.java:876)
	at com.google.gson.Gson.fromJson(Gson.java:799)
	at amidst.parsing.json.JsonReader.readReader(JsonReader.java:41)
	... 30 more
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 114 path $.biomeList[0].00
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1574)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:534)
	at com.google.gson.stream.JsonReader.skipValue(JsonReader.java:1237)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
	at com.google.gson.Gson.fromJson(Gson.java:861)
	... 32 more

[warning] Unable to load file: biome/MineClone 2.mt
[warning] amidst.parsing.FormatException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 122 path $.biomeList[0].00
	at amidst.parsing.json.JsonReader.readReader(JsonReader.java:48)
	at amidst.parsing.json.JsonReader.readLocation(JsonReader.java:25)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.createFromFile(BiomeProfileDirectory.java:223)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.visitProfiles(BiomeProfileDirectory.java:170)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.visitProfiles(BiomeProfileDirectory.java:162)
	at amidst.gui.main.menu.BiomeProfileMenuFactory.initParentMenu(BiomeProfileMenuFactory.java:169)
	at amidst.gui.main.menu.BiomeProfileMenuFactory.<init>(BiomeProfileMenuFactory.java:161)
	at amidst.gui.main.menu.AmidstMenuBuilder.create_Settings_BiomeProfile(AmidstMenuBuilder.java:161)
	at amidst.gui.main.menu.AmidstMenuBuilder.create_Settings(AmidstMenuBuilder.java:129)
	at amidst.gui.main.menu.AmidstMenuBuilder.createMenuBar(AmidstMenuBuilder.java:54)
	at amidst.gui.main.menu.AmidstMenuBuilder.<init>(AmidstMenuBuilder.java:36)
	at amidst.gui.main.PerMainWindowInjector.<init>(PerMainWindowInjector.java:114)
	at amidst.PerApplicationInjector.createMainWindow(PerApplicationInjector.java:122)
	at amidst.Application.displayMainWindow(Application.java:73)
	at amidst.Application.run(Application.java:55)
	at amidst.Amidst.doStartApplication(Amidst.java:171)
	at amidst.Amidst.lambda$startApplication$0(Amidst.java:162)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 122 path $.biomeList[0].00
	at com.google.gson.Gson.fromJson(Gson.java:876)
	at com.google.gson.Gson.fromJson(Gson.java:799)
	at amidst.parsing.json.JsonReader.readReader(JsonReader.java:41)
	... 30 more
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 122 path $.biomeList[0].00
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1574)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:534)
	at com.google.gson.stream.JsonReader.skipValue(JsonReader.java:1237)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
	at com.google.gson.Gson.fromJson(Gson.java:861)
	... 32 more

[warning] Unable to load file: biome/Minetest default.mt
[warning] amidst.parsing.FormatException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 115 path $.biomeList[0].00
	at amidst.parsing.json.JsonReader.readReader(JsonReader.java:48)
	at amidst.parsing.json.JsonReader.readLocation(JsonReader.java:25)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.createFromFile(BiomeProfileDirectory.java:223)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.visitProfiles(BiomeProfileDirectory.java:170)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.visitProfiles(BiomeProfileDirectory.java:162)
	at amidst.gui.main.menu.BiomeProfileMenuFactory.initParentMenu(BiomeProfileMenuFactory.java:169)
	at amidst.gui.main.menu.BiomeProfileMenuFactory.<init>(BiomeProfileMenuFactory.java:161)
	at amidst.gui.main.menu.AmidstMenuBuilder.create_Settings_BiomeProfile(AmidstMenuBuilder.java:161)
	at amidst.gui.main.menu.AmidstMenuBuilder.create_Settings(AmidstMenuBuilder.java:129)
	at amidst.gui.main.menu.AmidstMenuBuilder.createMenuBar(AmidstMenuBuilder.java:54)
	at amidst.gui.main.menu.AmidstMenuBuilder.<init>(AmidstMenuBuilder.java:36)
	at amidst.gui.main.PerMainWindowInjector.<init>(PerMainWindowInjector.java:114)
	at amidst.PerApplicationInjector.createMainWindow(PerApplicationInjector.java:122)
	at amidst.Application.displayMainWindow(Application.java:73)
	at amidst.Application.run(Application.java:55)
	at amidst.Amidst.doStartApplication(Amidst.java:171)
	at amidst.Amidst.lambda$startApplication$0(Amidst.java:162)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 115 path $.biomeList[0].00
	at com.google.gson.Gson.fromJson(Gson.java:876)
	at com.google.gson.Gson.fromJson(Gson.java:799)
	at amidst.parsing.json.JsonReader.readReader(JsonReader.java:41)
	... 30 more
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 115 path $.biomeList[0].00
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1574)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:534)
	at com.google.gson.stream.JsonReader.skipValue(JsonReader.java:1237)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
	at com.google.gson.Gson.fromJson(Gson.java:861)
	... 32 more

[warning] Unable to load file: biome/V6 biomes.mt
[warning] amidst.parsing.FormatException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 108 path $.biomeList[0].00
	at amidst.parsing.json.JsonReader.readReader(JsonReader.java:48)
	at amidst.parsing.json.JsonReader.readLocation(JsonReader.java:25)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.createFromFile(BiomeProfileDirectory.java:223)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.visitProfiles(BiomeProfileDirectory.java:170)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.visitProfiles(BiomeProfileDirectory.java:162)
	at amidst.gui.main.menu.BiomeProfileMenuFactory.initParentMenu(BiomeProfileMenuFactory.java:169)
	at amidst.gui.main.menu.BiomeProfileMenuFactory.<init>(BiomeProfileMenuFactory.java:161)
	at amidst.gui.main.menu.AmidstMenuBuilder.create_Settings_BiomeProfile(AmidstMenuBuilder.java:161)
	at amidst.gui.main.menu.AmidstMenuBuilder.create_Settings(AmidstMenuBuilder.java:129)
	at amidst.gui.main.menu.AmidstMenuBuilder.createMenuBar(AmidstMenuBuilder.java:54)
	at amidst.gui.main.menu.AmidstMenuBuilder.<init>(AmidstMenuBuilder.java:36)
	at amidst.gui.main.PerMainWindowInjector.<init>(PerMainWindowInjector.java:114)
	at amidst.PerApplicationInjector.createMainWindow(PerApplicationInjector.java:122)
	at amidst.Application.displayMainWindow(Application.java:73)
	at amidst.Application.run(Application.java:55)
	at amidst.Amidst.doStartApplication(Amidst.java:171)
	at amidst.Amidst.lambda$startApplication$0(Amidst.java:162)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 108 path $.biomeList[0].00
	at com.google.gson.Gson.fromJson(Gson.java:876)
	at com.google.gson.Gson.fromJson(Gson.java:799)
	at amidst.parsing.json.JsonReader.readReader(JsonReader.java:41)
	... 30 more
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 108 path $.biomeList[0].00
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1574)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:534)
	at com.google.gson.stream.JsonReader.skipValue(JsonReader.java:1237)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
	at com.google.gson.Gson.fromJson(Gson.java:861)
	... 32 more

[warning] Unable to load file: biome/VoxelGarden.mt
[warning] amidst.parsing.FormatException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 114 path $.biomeList[0].00
	at amidst.parsing.json.JsonReader.readReader(JsonReader.java:48)
	at amidst.parsing.json.JsonReader.readLocation(JsonReader.java:25)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.createFromFile(BiomeProfileDirectory.java:223)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.visitProfiles(BiomeProfileDirectory.java:170)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.visitProfiles(BiomeProfileDirectory.java:162)
	at amidst.gui.main.menu.BiomeProfileMenuFactory.initParentMenu(BiomeProfileMenuFactory.java:169)
	at amidst.gui.main.menu.BiomeProfileMenuFactory.<init>(BiomeProfileMenuFactory.java:161)
	at amidst.gui.main.menu.AmidstMenuBuilder.create_Settings_BiomeProfile(AmidstMenuBuilder.java:161)
	at amidst.gui.main.menu.AmidstMenuBuilder.create_Settings(AmidstMenuBuilder.java:129)
	at amidst.gui.main.menu.AmidstMenuBuilder.createMenuBar(AmidstMenuBuilder.java:54)
	at amidst.gui.main.menu.AmidstMenuBuilder.<init>(AmidstMenuBuilder.java:36)
	at amidst.gui.main.PerMainWindowInjector.<init>(PerMainWindowInjector.java:114)
	at amidst.PerApplicationInjector.createMainWindow(PerApplicationInjector.java:122)
	at amidst.Application.displayMainWindow(Application.java:73)
	at amidst.Application.run(Application.java:55)
	at amidst.Amidst.doStartApplication(Amidst.java:171)
	at amidst.Amidst.lambda$startApplication$0(Amidst.java:162)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 114 path $.biomeList[0].00
	at com.google.gson.Gson.fromJson(Gson.java:876)
	at com.google.gson.Gson.fromJson(Gson.java:799)
	at amidst.parsing.json.JsonReader.readReader(JsonReader.java:41)
	... 30 more
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 114 path $.biomeList[0].00
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1574)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:534)
	at com.google.gson.stream.JsonReader.skipValue(JsonReader.java:1237)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
	at com.google.gson.Gson.fromJson(Gson.java:861)
	... 32 more

[info] Successfully loaded remote version list.
[info] There are no updates available.
[info] Not writing to seed history file, because it does not exist: history.txt
[info] increasing fragment cache size from 0 to 1024
[info] fragment cache size increased to 1024

**Comment by Treer** [comment]
Well that's weird, it looks like the directory might not be the problem at all. 

    Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 114 path $.biomeList[0].00

in all these errors it expected ':' after the first floating point value in the file. Some json libs have had a locale dependent parser bug, I doubt this one does, but I should ask how your locale formats decimal points.

**Comment by Treer** [comment]
I think I know the problem. I'm probably writing the .mt files using a function that's aware of your locale and using a comma for the decimal separator.

So instead of the end of line 2 of voxelgarden.mt looking like this:

    "heat_point": 30.00, "humidity_point": 40.00 },

yours probably looks like this:

    "heat_point": 30,00, "humidity_point": 40,00 },

thus the MalformedJsonExceptions. I'll fix when I get home. Thanks for providing that info.

**Comment by Treer** [comment]
Can you confirm that the latest release fixes this issue?

**Important:** You'll have to delete the existing .mt files in your biomes directory, as they are malformed and amidstest won't overwrite existing files.

**Comment by tacotexmex** [comment]
That solved it. Now I can use 30-biomes again. Thanks Treer!
